TITLE    = VZG presentation
AUTHOR   = Some author
DATE     = 2013-12-24
VERSION  = none
LANGUAGE = english

include ../../Makefile

# TODO: simplify creation of slides - put into local.make?
TEX_TEMPLATE = ../../templates/vzg-slides.latex
TEX_ARGS     += --slide-level 2 $(TOC) -t beamer 
TEX_VARS     = -V documentclass=beamer
